### ISSUE TITLE
elf has no sh_type::dynstr definition but used in it

### ISSUE THREAD

**Issue by yufengzjj** [kaitai-io/kaitai_struct_formats#253]
int elf.ksy sh_type defines without dynstr:
```ksy
 sh_type:
    0: null_type
    1: progbits
    2: symtab
    3: strtab
    4: rela
    5: hash
    6: dynamic
    7: note
    8: nobits
    9: rel
    10: shlib
    11: dynsym
    14: init_array
    15: fini_array
    16: preinit_array
    17: group
    18: symtab_shndx
```
but then use it in:
```ksy
         body:
            io: _root._io
            pos: ofs_body
            size: len_body
            type:
              switch-on: type
              cases:
                'sh_type::dynamic': dynamic_section
                'sh_type::strtab': strings_struct
                'sh_type::dynsym': dynsym_section
                'sh_type::dynstr': strings_struct
          name:
```
the generated python code:
```python
 class ShType(Enum):
        null_type = 0
        progbits = 1
        symtab = 2
        strtab = 3
        rela = 4
        hash = 5
        dynamic = 6
        note = 7
        nobits = 8
        rel = 9
        shlib = 10
```
and generated python use the dynstr:
```python
  @property
            def body(self):
                if hasattr(self, '_m_body'):
                    return self._m_body if hasattr(self, '_m_body') else None

                io = self._root._io
                _pos = io.pos()
                io.seek(self.ofs_body)
                if self._is_le:
                    _on = self.type
                    if _on == self._root.ShType.dynamic:
                        self._raw__m_body = io.read_bytes(self.len_body)
                        io = KaitaiStream(BytesIO(self._raw__m_body))
                        self._m_body = self._root.EndianElf.DynamicSection(io, self, self._root, self._is_le)
                    elif _on == self._root.ShType.strtab:
                        self._raw__m_body = io.read_bytes(self.len_body)
                        io = KaitaiStream(BytesIO(self._raw__m_body))
                        self._m_body = self._root.EndianElf.StringsStruct(io, self, self._root, self._is_le)
                    elif _on == self._root.ShType.dynstr: # !!!!!!here
                        self._raw__m_body = io.read_bytes(self.len_body)
                        io = KaitaiStream(BytesIO(self._raw__m_body))
                        self._m_body = self._root.EndianElf.StringsStruct(io, self, self._root, self._is_le)
                    elif _on == self._root.ShType.dynsym:
                        self._raw__m_body = io.read_bytes(self.len_body)
                        io = KaitaiStream(BytesIO(self._raw__m_body))
                        self._m_body = self._root.EndianElf.DynsymSection(io, self, self._root, self._is_le)
                    else:
                        self._m_body = io.read_bytes(self.len_body)
                else:
```
the generated python code would get an error:

> Traceback (most recent call last):
>   File "/root/remote/mdeobfs/kk.py", line 171, in <module>
>     k25(486546801)
>   File "/root/remote/mdeobfs/kk.py", line 33, in k25
>     eu.write_mem(image_base + __text_sec.addr, __text_sec.body)
>   File "/root/remote/mdeobfs/elf.py", line 1069, in body
>     elif _on == self._root.ShType.dynstr:
>   File "/root/.pyenv/versions/3.7.4/lib/python3.7/enum.py", line 349, in __getattr__
>     raise AttributeError(name) from None
> AttributeError: dynstr

@GreyCat I updated the details

**Comment by GreyCat** [comment]
Can you elaborate what do you mean by this?

**Comment by armijnhemel** [comment]
> Can you elaborate what do you mean by this?

In the ELF specification SHT_STRTAB and SHT_DYNSTR are equivalent. Depending on which program you look at, or what documentation, it will either refer to SHT_STRTAB or SHT_DYNSTR. The correct solution here is to delete

```
'sh_type::dynstr': strings_struct
```

**Comment by armijnhemel** [comment]
Reference: https://docs.oracle.com/cd/E19683-01/816-1386/6m7qcoblj/index.html

Search for SHT_DYNSTR will only result in one hit. there is no section value type associated with it.
