### ISSUE TITLE
Extraction and parsing of rsrc in Microsoft PE files

### ISSUE THREAD

**Issue by OlivierCavadenti** [kaitai-io/kaitai_struct_formats#350]
Hi,

I have download both Microsoft PE and Windows resource file parsers and I try to use the second to parse the rsrc section of the first.

I try this in Kotlin: 

```
    MicrosoftPe.fromFile(path)
        .pe()
        .sections()
        .forEach { section ->
            if (section.name() == ".rsrc") {
                WindowsResourceFile(ByteBufferKaitaiStream(section.body()))
                    .resources().forEach {
                        println(it.name().asString())
                    }
            }
        }
```
I have this error : 

```
Exception in thread "main" java.lang.IllegalArgumentException: Java byte arrays can be indexed only up to 31 bits, but 2147483856 size was requested
	at io.kaitai.struct.KaitaiStream.toByteArrayLength(KaitaiStream.java:294)
	at io.kaitai.struct.ByteBufferKaitaiStream.readBytes(ByteBufferKaitaiStream.java:273)
	at parsers.executable.WindowsResourceFile$Resource._read(WindowsResourceFile.java:139)
	at parsers.executable.WindowsResourceFile$Resource.<init>(WindowsResourceFile.java:126)
	at parsers.executable.WindowsResourceFile._read(WindowsResourceFile.java:63)
	at parsers.executable.WindowsResourceFile.<init>(WindowsResourceFile.java:56)
	at parsers.executable.WindowsResourceFile.<init>(WindowsResourceFile.java:45)
```

I assume that the body of the section have more complex structure that just a list of resources data but I cant find any way to successfully parse these resources with WindowsResourceFile.

Cheers

**Comment by bvanheu** [comment]
OlivierCavandenti: You can't parse the `.rsrc` section with the `WindowsResourceFile` parser because that section is not a `WindowsResourceFile`.

You can try with this PR maybe:
https://github.com/kaitai-io/kaitai_struct_formats/pull/344

**Comment by OlivierCavadenti** [comment]
@bvanheu hi, thanks for the PR, I will check if I can achieve something.
Thanks for your answers,
Cheers
